# Generated by Django 3.2 on 2022-08-24 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='dishes',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='dishes',
        ),
    ]
